### ISSUE TITLE
undefined method publishable_key on lates

### ISSUE THREAD

**Issue by adenta** [clerk/clerk-sdk-ruby#74]
repro:
1. install clerk
2. create a clerk.rb initializer with:
```
Clerk.configure do |c|
  c.api_key = ENV['CLERK_SECRET_KEY']
  c.publishable_key = ENV['VITE_CLERK_PUBLISHABLE_KEY']
  c.logger = Logger.new(STDOUT)
end
```
3. launch rails c

```
➜  cardstock git:(main) ✗ rails c
/Users/andrew/cardstock/config/initializers/clerk.rb:3:in `block in <main>': undefined method `publishable_key=' for an instance of Clerk::Config (NoMethodError)

  c.publishable_key = ENV['VITE_CLERK_PUBLISHABLE_KEY']
   ^^^^^^^^^^^^^^^^^^
        from /Users/andrew/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/clerk-sdk-ruby-3.3.0/lib/clerk.rb:10:in `configure'
        from /Users/andrew/cardstock/config/initializers/clerk.rb:1:in `<main>'
        from /Users/andrew/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/railties-8.0.0/lib/rails/engine.rb:693:in `load'
        from /Users/andrew/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/railties-8.0.0/lib/rails/engine.rb:693:in `block in load_config_initializer'
        from /Users/andrew/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/activesupport-8.0.0/lib/active_support/notifications.rb:212:in `instrument'
        from /Users/andrew/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/railties-8.0.0/lib/rails/engine.rb:692:in `load_config_initializer'
        from /Users/andrew/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/railties-8.0.0/lib/rails/engine.rb:646:in `block (2 levels) in <class:Engine>'
        from /Users/andrew/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/railties-8.0.0/lib/rails/engine.rb:645:in `each'
        from /Users/andrew/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/railties-8.0.0/lib/rails/engine.rb:645:in `block in <class:Engine>'
        from /Users/andrew/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/railties-8.0.0/lib/rails/initializable.rb:32:in `instance_exec'
        from /Users/andrew/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/railties-8.0.0/lib/rails/initializable.rb:32:in `run'
        from /Users/andrew/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/railties-8.0.0/lib/rails/initializable.rb:61:in `block in run_initializers'
        from /Users/andrew/.rbenv/versions/3.3.2/lib/ruby/3.3.0/tsort.rb:231:in `block in tsort_each'
        from /Users/andrew/.rbenv/versions/3.3.2/lib/ruby/3.3.0/tsort.rb:353:in `block (2 levels) in each_strongly_connected_component'
        from /Users/andrew/.rbenv/versions/3.3.2/lib/ruby/3.3.0/tsort.rb:425:in `block (2 levels) in each_strongly_connected_component_from'
        from /Users/andrew/.rbenv/versions/3.3.2/lib/ruby/3.3.0/tsort.rb:434:in `each_strongly_connected_component_from'
        from /Users/andrew/.rbenv/versions/3.3.2/lib/ruby/3.3.0/tsort.rb:424:in `block in each_strongly_connected_component_from'
        from /Users/andrew/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/railties-8.0.0/lib/rails/initializable.rb:50:in `each'
        from /Users/andrew/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/railties-8.0.0/lib/rails/initializable.rb:50:in `tsort_each_child'
        from /Users/andrew/.rbenv/versions/3.3.2/lib/ruby/3.3.0/tsort.rb:418:in `call'
        from /Users/andrew/.rbenv/versions/3.3.2/lib/ruby/3.3.0/tsort.rb:418:in `each_strongly_connected_component_from'
        from /Users/andrew/.rbenv/versions/3.3.2/lib/ruby/3.3.0/tsort.rb:352:in `block in each_strongly_connected_component'
        from /Users/andrew/.rbenv/versions/3.3.2/lib/ruby/3.3.0/tsort.rb:350:in `each'
        from /Users/andrew/.rbenv/versions/3.3.2/lib/ruby/3.3.0/tsort.rb:350:in `call'
        from /Users/andrew/.rbenv/versions/3.3.2/lib/ruby/3.3.0/tsort.rb:350:in `each_strongly_connected_component'
        from /Users/andrew/.rbenv/versions/3.3.2/lib/ruby/3.3.0/tsort.rb:229:in `tsort_each'
        from /Users/andrew/.rbenv/versions/3.3.2/lib/ruby/3.3.0/tsort.rb:208:in `tsort_each'
        from /Users/andrew/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/railties-8.0.0/lib/rails/initializable.rb:60:in `run_initializers'
        from /Users/andrew/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/railties-8.0.0/lib/rails/application.rb:440:in `initialize!'
        from /Users/andrew/cardstock/config/environment.rb:5:in `<main>'
        from /Users/andrew/.rbenv/versions/3.3.2/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
        from /Users/andrew/.rbenv/versions/3.3.2/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
        from /Users/andrew/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /Users/andrew/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/zeitwerk-2.7.1/lib/zeitwerk/core_ext/kernel.rb:34:in `require'
        from /Users/andrew/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/railties-8.0.0/lib/rails/application.rb:416:in `require_environment!'
        from /Users/andrew/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/railties-8.0.0/lib/rails/command/actions.rb:20:in `boot_application!'
        from /Users/andrew/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/railties-8.0.0/lib/rails/commands/console/console_command.rb:86:in `perform'
        from /Users/andrew/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor/command.rb:28:in `run'
        from /Users/andrew/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor/invocation.rb:127:in `invoke_command'
        from /Users/andrew/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/railties-8.0.0/lib/rails/command/base.rb:178:in `invoke_command'
        from /Users/andrew/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor.rb:538:in `dispatch'
        from /Users/andrew/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/railties-8.0.0/lib/rails/command/base.rb:73:in `perform'
        from /Users/andrew/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/railties-8.0.0/lib/rails/command.rb:65:in `block in invoke'
        from /Users/andrew/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/railties-8.0.0/lib/rails/command.rb:143:in `with_argv'
        from /Users/andrew/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/railties-8.0.0/lib/rails/command.rb:63:in `invoke'
        from /Users/andrew/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/railties-8.0.0/lib/rails/commands.rb:18:in `<main>'
        from /Users/andrew/.rbenv/versions/3.3.2/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
        from /Users/andrew/.rbenv/versions/3.3.2/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
        from /Users/andrew/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
```

using 4.0.0.beta3 for now

**Comment by tmilewski** [comment]
Seeing as you're using 4.0.0.beta3, and that we've since released 4.0.0, I'm going to close this issue. Please feel free to reopen, if this issue still persists.
